# Generated by Django 5.1.6 on 2025-04-03 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='address',
        ),
        migrations.RemoveField(
            model_name='store',
            name='city',
        ),
        migrations.RemoveField(
            model_name='store',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='store',
            name='email',
        ),
        migrations.RemoveField(
            model_name='store',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='store',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='store',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='store',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='store',
            name='state',
        ),
    ]
