# Generated by Django 5.1.6 on 2025-04-03 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_remove_store_address_remove_store_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='restaurant name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description of the restaurant', null=True)),
                ('address', models.TextField(help_text='Full address of the restaurant')),
                ('city', models.CharField(help_text='City where the restaurant is located', max_length=100)),
                ('state', models.CharField(help_text='State where the restaurant is located', max_length=100)),
                ('pincode', models.CharField(help_text='Postal code of the restaurant', max_length=10)),
                ('phone', models.CharField(blank=True, help_text='restaurant contact number', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='restaurant email address', max_length=254, null=True)),
                ('opening_time', models.TimeField(help_text='Opening time of the restaurant')),
                ('closing_time', models.TimeField(help_text='Closing time of the restaurant')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the restaurant is active or not')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the restaurant was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated timestamp')),
                ('owner', models.ForeignKey(help_text='User who owns the restaurant.', limit_choices_to={'role': 'shop_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='stores.store')),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
                'ordering': ['-created_at'],
            },
        ),
    ]
