# Generated by Django 5.1.6 on 2025-04-04 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_owner'),
        ('stores', '0002_remove_store_address_remove_store_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.OneToOneField(help_text='User who owns the restaurant.', on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='stores.store'),
        ),
    ]
