# Generated by Django 5.1.6 on 2025-04-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_restaurant_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='owner',
            new_name='store',
        ),
    ]
